#%RAML 1.0 DataType

description: Beer Breweries
type: object
properties:
  name?:
    description: Beer Breweries name
    type: string
  country?:
    description: Beer Breweries country
    type: string
  city?:
    description: Beer Breweries city
    type: string

example:
  name: "Youngs & Company Brewery"
  country: "England"
  city: "London"